TSPPproject/Models/Refugee.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace TSPPproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refugee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Refugee()
        {
            this.What_helps = new HashSet<What_helps>();
        }
    
        public int Id_Refugee { get; set; }
        [Required]
        [Display(Name = "First name")]
        public string FirstName { get; set; }
        [Required]
        [Display(Name = "Last name")]
        public string LastName { get; set; }
        public int Id_Location { get; set; }
        [Phone]
        [Display(Name = "Phone Number")]
        public string Phone { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
    
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<What_helps> What_helps { get; set; }
    }
}

TSPPproject/Models/ViewModels/RefugeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TSPPproject.Models;

namespace TSPPproject.Models.ViewModels
{
    public class RefugeeViewModel
    {
        public IEnumerable<Refugee> Volunteers { get; set; }
        public IEnumerable<What_helps> WhatHelpses { get; set; }
    }
}

TSPPproject/Controllers/RefugeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TSPPproject.Models;
using TSPPproject.Models.ViewModels;
using PagedList;

namespace TSPPproject.Controllers
{
    public class RefugeesController : Controller
    {
        private VolunteerHelpEntities db = new VolunteerHelpEntities();

        // GET: Refugees
        public ActionResult Index(int? id, int? whatHelpsID, int? selectedLocation, string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Location" ? "location_desc" : "Location";



            var viewModel = new RefugeeViewModel();

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;



            //if (id != null)
            //{
            //    ViewBag.Id_Volunteer = id.Value;
            //    viewModel.WhatHelpses = viewModel.Volunteers.Single(i => i.Id_Volunteer == id.Value).What_helps;
            //}

            var locations = db.Locations.OrderBy(q => q.Name).ToList();
            ViewBag.selectedLocation = new SelectList(locations, "Id_Location", "Name", selectedLocation);
            var Id_Location = selectedLocation.GetValueOrDefault();

            var refugee = db.Refugees
                .Where(c => !selectedLocation.HasValue || c.Id_Location == Id_Location)
                .OrderBy(d => d.Id_Refugee)
                .Include(d => d.Location)
                .Include(i => i.What_helps);


            if (!String.IsNullOrEmpty(searchString))
            {
                refugee = refugee.Where(s => s.LastName.Contains(searchString)
                                       || s.FirstName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    refugee = refugee.OrderByDescending(s => s.LastName);
                    break;
                case "Date":
                    refugee = refugee.OrderBy(s => s.Id_Location);
                    break;
                case "date_desc":
                    refugee = refugee.OrderByDescending(s => s.Id_Location);
                    break;
                default:  // Name ascending 
                    refugee = refugee.OrderBy(s => s.LastName);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);



            //if (id != null)
            //{
            //    ViewBag.Id_Volunteer = id.Value;
            //    viewModel.WhatHelpses = viewModel.Volunteers.Where(
            //        i => i.Id_Refugee == id.Value).Single().What_helps;
            //}

            return View(refugee.ToPagedList(pageNumber, pageSize));
        }

        // GET: Volunteers/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var refugee = db.Refugees.Find(id);
            if (refugee == null)
            {
                return HttpNotFound();
            }
            return View(refugee);
        }

        // GET: Volunteers/Create
        public ActionResult Create()
        {
            var refugee = new Refugee();
            refugee.What_helps = new List<What_helps>();
            PopulateAssignedHelpData(refugee);
            PopulateLocationDropDownList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Refugee refugee, string[] selectedCourses)
        {
            if (selectedCourses != null)
            {
                refugee.What_helps = new List<What_helps>();
                foreach (var help in selectedCourses)
                {
                    var helpToAdd = db.What_helps.Find(int.Parse(help));
                    refugee.What_helps.Add(helpToAdd);
                }
            }
            if (ModelState.IsValid)
            {
                db.Refugees.Add(refugee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            PopulateAssignedHelpData(refugee);
            PopulateLocationDropDownList(refugee.Id_Refugee);

            return View(refugee);
        }

        private void PopulateAssignedHelpData(Refugee refugee)
        {
            var allHelps = db.What_helps;
            var refugeeGetHelps = new HashSet<int>(refugee.What_helps.Select(c => c.Id_What_helps));
            var viewModel = new List<AssignedHelpData>();
            foreach (var help in allHelps)
            {
                viewModel.Add(new AssignedHelpData()
                {
                    Id_What_helps = help.Id_What_helps,
                    Name = help.Name,
                    Type_of_help = help.Type_of_help,
                    Assigned = refugeeGetHelps.Contains(help.Id_What_helps)
                });
            }
            ViewBag.What_helps = viewModel;
        }
        private void PopulateLocationDropDownList(object selectedLocation = null)
        {
            var locationQuery = from d in db.Locations
                                orderby d.Name
                                select d;
            ViewBag.Id_Location = new SelectList(locationQuery, "Id_Location", "Name", selectedLocation);
        }

        // GET: Volunteers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var refugee = db.Refugees
                .Include(d => d.Location)
                .Include(i => i.What_helps)
                .Where(i => i.Id_Refugee == id)
                .Single();
            PopulateAssignedHelpData(refugee);
            if (refugee == null)
            {
                return HttpNotFound();
            }
            PopulateLocationDropDownList(refugee.Id_Location);
            return View(refugee);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, string[] selectedCourses)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var refugeeToUpdate = db.Refugees
            .Include(d => d.Location)
            .Include(i => i.What_helps)
            .Where(i => i.Id_Refugee == id)
            .Single();
            if (TryUpdateModel(refugeeToUpdate, "",
               new string[] { "FirstName", "LastName", "Id_Location", "Phone", "Email" }))
            {
                try
                {
                    UpdateInstructorHelps(selectedCourses, refugeeToUpdate);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            PopulateAssignedHelpData(refugeeToUpdate);
            PopulateLocationDropDownList(refugeeToUpdate.Id_Location);
            return View(refugeeToUpdate);
        }
        private void UpdateInstructorHelps(string[] selectedCourses, Refugee refugeeToUpdate)
        {
            if (selectedCourses == null)
            {
                refugeeToUpdate.What_helps = new List<What_helps>();
                return;
            }

            var selectedHelpHS = new HashSet<string>(selectedCourses);
            var refugeeGetHelps = new HashSet<int>
                (refugeeToUpdate.What_helps.Select(c => c.Id_What_helps));
            foreach (var help in db.What_helps)
            {
                if (selectedHelpHS.Contains(help.Id_What_helps.ToString()))
                {
                    if (!refugeeGetHelps.Contains(help.Id_What_helps))
                    {
                        refugeeToUpdate.What_helps.Add(help);
                    }
                }
                else
                {
                    if (refugeeGetHelps.Contains(help.Id_What_helps))
                    {
                        refugeeToUpdate.What_helps.Remove(help);
                    }
                }
            }
        }

        // GET:  unteers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Refugee refugee = db.Refugees.Find(id);
            if (refugee == null)
            {
                return HttpNotFound();
            }
            return View(refugee);
        }

        // POST: Course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var refugee = db.Refugees
            .Include(d => d.Location)
            .Include(i => i.What_helps)
            .Where(i => i.Id_Refugee == id)
            .Single();
            db.Refugees.Remove(refugee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

TSPPproject/Views/Refugees/Create.cshtml
@model TSPPproject.Models.Refugee

@{
    ViewBag.Title = "Create";
}




@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Постраждала особа</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, "Ім'я", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, "Прізвище", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Location, "Розташування", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_Location", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Location, "Допомогу потребує?", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-offset-2 col-md-10">
                <table>
                    <tr>
                        @{
                            int cnt = 0;
                            List<TSPPproject.Models.ViewModels.AssignedHelpData> helps = ViewBag.What_helps;


                            foreach (var help in helps)
                            {

                                if (cnt++ % 3 == 0)
                                {
                                    @: </tr><tr>
                            }
                                @:<td>
                                    <input type="checkbox"
                                           name="selectedCourses"
                                           value="@help.Id_What_helps"
                                           @(Html.Raw(help.Assigned ? "checked=\"checked\"" : "")) />
                                    @: @help.Name
                                @:</td>
                        }
                            @:</tr>
                        }
                    </table>
                </div>
            </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, "Телефон", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Повернутись на попередню сторінку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TSPPproject/Views/Refugees/Delete.cshtml
@model TSPPproject.Models.Refugee

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Постраждала особа</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TSPPproject/Views/Refugees/Details.cshtml
@model TSPPproject.Models.Refugee

@{
    ViewBag.Title = "Details";
}



<div>
    <h4>Постраждала особа</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Ім'я")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayName("Прізвище")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayName("Телефон")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayName("Розташування")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id_Refugee }) |
    @Html.ActionLink("Повернутись на попередню сторінку", "Index")
</p>

TSPPproject/Views/Refugees/Edit.cshtml
@model TSPPproject.Models.Refugee

@{
    ViewBag.Title = "Edit";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Постраждала особа</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_Refugee)

        @Html.LabelFor(model => model.FirstName, "Ім'я", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, "Прізвище", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Location, "Розташування", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_Location", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Location, "Допомогу потребує?", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-offset-2 col-md-10">
                <table>
                    <tr>
                        @{
                            int cnt = 0;
                            List<TSPPproject.Models.ViewModels.AssignedHelpData> helps = ViewBag.What_helps;


                            foreach (var help in helps)
                            {

                                if (cnt++ % 3 == 0)
                                {
                                    @:</tr><tr>
                            }
                                @:<td>
                                    <input type="checkbox"
                                           name="selectedCourses"
                                           value="@help.Id_What_helps"
                                           @(Html.Raw(help.Assigned ? "checked=\"checked\"" : "")) />
                                    @: @help.Name
                                    @:</td>
                        }
                            @:</tr>
                        }
                    </table>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone, "Телефон", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Повернутись на попередню сторінку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TSPPproject/Views/Refugees/Index.cshtml
@model PagedList.IPagedList<TSPPproject.Models.Refugee>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}

<h2>Особи, які потребують допомоги</h2>

@if (Request.IsAuthenticated)
{
    <p>
        @Html.ActionLink("Добавити особу", "Create")
    </p>
    using (Html.BeginForm("Index", "Refugees", FormMethod.Get))
    {
        <p>
            Пошук по імені: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" />
        </p>
    }
    <table class="table">
        <tr>
            <th>Ім'я</th>
            <th>@Html.ActionLink("Прізвище", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })</th>
            <th>Телефон</th>
            <th>Email</th>
            <th>Допомогу потребує?</th>
            <th>@Html.ActionLink("Розташуванння", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })</th>


            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @*<ul>
                            @foreach (var help in item.What_helps)
                            {
                                <li>@help.Name</li>
                            }
                        </ul>*@
                    @{
                        foreach (var help in item.What_helps)
                        {
                            @help.Id_What_helps @: @help.Name <br />
                    }
                    }

                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Location.Name)
                </td>
                <td>

                    @Html.ActionLink("Edit", "Edit", new { id = item.Id_Refugee }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id_Refugee }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id_Refugee })
                </td>
            </tr>
                        }

    </table>
                        }
                        else
                        {

                            <p>
                                @Html.ActionLink("Добавити особу", "Create")
                            </p>
                            using (Html.BeginForm("Index", "Refugees", FormMethod.Get))
                            {
                                <p>
                                    Пошук по імені: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                                    <input type="submit" value="Search" />
                                </p>
                            }
                            <table class="table">
                                <tr>
                                    <th>Ім'я</th>
                                    <th>@Html.ActionLink("Прізвище", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })</th>
                                    <th>Телефон</th>
                                    <th>Email</th>
                                    <th>Допомогу потребує?</th>
                                    <th>@Html.ActionLink("Розташуванння", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })</th>


                                    <th></th>
                                </tr>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.FirstName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.LastName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Phone)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Email)
                                        </td>
                                        <td>
                                            @*<ul>
                                                    @foreach (var help in item.What_helps)
                                                    {
                                                        <li>@help.Name</li>
                                                    }
                                                </ul>*@
                                            @{
                                                foreach (var help in item.What_helps)
                                                {
                                                    @help.Id_What_helps @: @help.Name <br />
                    }
                                            }

                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.Location.Name)
                                        </td>
                                        <td>

                                            @*@Html.ActionLink("Edit", "Edit", new { id = item.Id_Refugee }) |*@
                                            @Html.ActionLink("Details", "Details", new { id = item.Id_Refugee }) |
                                            @*@Html.ActionLink("Delete", "Delete", new { id = item.Id_Refugee })*@
                                        </td>
                                    </tr>
                                                }

                            </table>
                                                }

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))